apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: dot
  annotations:
    meta.crossplane.io/maintainer: Viktor Farcic | @vfarcic | viktor@farcic.com
    meta.crossplane.io/source: github.com/vfarcic/upbound-dot
    meta.crossplane.io/license: MIT
    meta.crossplane.io/description: |
      A bunch of Configurations
    meta.crossplane.io/readme: |
      A bunch of Configurations
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
  - provider: crossplane/provider-sql
    version: ">=v0.5.0"
  - provider: xpkg.upbound.io/crossplane-contrib/provider-helm
    version: ">=v0.13.0"
  - provider: xpkg.upbound.io/crossplane-contrib/provider-kubernetes
    version: ">=v0.6.0"
  - provider: xpkg.upbound.io/upbound/provider-gcp
    version: ">=v0.30.0"
  - provider: xpkg.upbound.io/upbound/provider-aws
    version: ">=v0.32.0"
  - provider: xpkg.upbound.io/upbound/provider-azure
    version: ">=v0.30.0"
  - provider: xpkg.upbound.io/devops-toolkit/dot-sql
    version: ">=v0.7.14"